### ISSUE TITLE
define global APIKEY security instead of the token param

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1109]
Now every path that uses the oauth security also defines a token param, that allows to pass the token in the query in case the user is too stupid to use a correct js library.

There is already a way to specify the API allows to auth using a token in the query : define an APIKEY security. https://swagger.io/docs/specification/2-0/authentication/api-keys/ 

The gain from using it is : less data that is not related to the path in the path.

I propose to 

1. Add a security with type APIKEY
 example :
```
     securityDefinitions:
       # this one is already present
       evesso
       # /path?token=qwerqwer123123
       querytoken:
         type: apiKey
         in: query
         name: token
```

2. use this security in every path that already uses the security evesso.
example, path /v1/characters/{character_id}/attributes/ would have in get/security : 
```
    - evesso:"esi-skills.read_skills.v1"
    - querytoken
```

3. remove the token parameter from every path, and its definition in the /parameters
