### ISSUE TITLE
/universe/types/ endpoint no longer returns German or Russian translated names

### ISSUE THREAD

**Issue by evanova** [esi/esi-issues#1180]
# Bug

The "types" endpoint returns English names instead of localized ones when requested for German or Russian. This does not happen with other languages and the descriptions are not affected.

## Request

GET https://esi.evetech.net/latest/universe/types/6/
Content-Type: application/json
Accept-Language: de

The same applies using "ru" for accept-language. Note that capitalization ("DE" vs "de") does not make any difference.

## Response

HTTP/1.1 200 OK

Response code: 200 (OK); Time: 477ms; Content length: 656 bytes

### Status Code

200

### Headers

Date: Mon, 16 Mar 2020 10:55:14 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 671
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age: 600
Allow: GET,HEAD,OPTIONS
Cache-Control: public
**Content-Language: de**
Etag: W/"00dacb7eb99823ee51e9f81b85ef8389b9117b37f448fa88fc7bfb08"
Expires: Mon, 16 Mar 2020 11:05:00 GMT
Last-Modified: Sat, 14 Mar 2020 11:01:59 GMT
Strict-Transport-Security: max-age=31536000
Vary: Accept-Language
X-Esi-Error-Limit-Remain: 100
X-Esi-Error-Limit-Reset: 46
X-Esi-Request-Id: 57616db6-ddb4-4621-a321-ae80c1d05c47

### Body

{
    "capacity": 0.0,
    "description": "Dieser Hauptreihenstern gehört einer Klasse an, die sich oft durch eine gelbe oder gelblich-orange Farbe auszeichnet und über den gewaltigen Wasserstofffusionsprozess im Herzen des Sterns eine enorme Menge Energie erzeugt und ausstrahlt.\n\n\n\nIm Orbit dieser Planeten können sowohl terrestrische Planeten als auch Gasriesen in unterschiedlicher Anzahl gefunden werden, von denen sich einer oder mehrere in der bewohnbaren Zone befindet.",
    "graphic_id": 21457,
    "group_id": 6,
    "mass": 1000000000000000000.0,
    **"name": "Sun G5 (Yellow)",**
    "packaged_volume": 1.0,
    "portion_size": 1,
    "published": false,
    "radius": 10000.0,
    "type_id": 6,
    "volume": 1.0
}

## Expected

Example response for French - the name is translated correctly to "Soleil G5 (jaune)". 

{
    "capacity": 0.0,
    "description": "Communément jaunes ou jaune orangé, ces étoiles de la séquence principale génèrent et émettent de l'énergie par fusion des noyaux d'hydrogène emprisonnés dans le cœur. Leur écosphère stellaire engendre la formation de planètes géantes de type terrestre ou gazeux, parmi lesquelles quelques spécimens gravitent souvent en zone habitable.",
    "graphic_id": 21457,
    "group_id": 6,
    "mass": 1000000000000000000.0,
    **"name": "Soleil G5 (jaune)",**
    "packaged_volume": 1.0,
    "portion_size": 1,
    "published": false,
    "radius": 10000.0,
    "type_id": 6,
    "volume": 1.0
}

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [X] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

**Comment by lukasni** [comment]
Just checked this against the latest SDE, the same problem seems to exist there.

```yaml
6:
    description:
        de: 'Dieser Hauptreihenstern [...]'
        en: "A main-sequence stellar body [...]"
        fr: Communément jaunes [...]
        ru: 'Звезда главной [...]'
        zh: '一种主星序星体 [...]'
    graphicID: 21457
    groupID: 6
    mass: 1000000000000000000
    name:
        de: Sun G5 (Yellow)
        en: Sun G5 (Yellow)
        fr: Soleil G5 (jaune)
        ja: 恒星G5（イエロー）
        ru: Sun G5 (Yellow)
        zh: 恒星G5(黄色)
```

In fact, the same persists in game, too. So this doesn't appear to be an issue with ESI but with the localization not being applied correctly in game.

![image](https://user-images.githubusercontent.com/5263957/77360107-01788e80-6d0a-11ea-861b-9f87b2964169.png)
