### ISSUE TITLE
Total quantity from /characters/{character_id}/industry/jobs/

### ISSUE THREAD

**Issue by Blacksmoke16** [esi/esi-issues#992]
# Feature Request
## Use case

The industry jobs endpoint returns the number of runs that are being executed but there is no way to determine how many total units will be produced.

One solution would be add a new field like `quantity_per_run` which would represent how many units that would be produced per run of a blueprint.  Then the total quantity of that job would be `quantity_per_run` * `runs`.

Another solution would be to add this to the response for a given type, (i would have to look into it more if it would be a dogma attribute or something?).  Then the user would have to look that up to determine total quantity being produced in each job slot. 

## Authentication

* esi-industry.read_character_jobs.v1
* esi-industry.read_corporation_jobs.v1

## Example return

Option 1

```json
[
  {
    "activity_id": 1,
    "blueprint_id": 1015116533326,
    "blueprint_location_id": 60006382,
    "blueprint_type_id": 883,
    "cost": 118.01,
    "duration": 548,
    "end_date": "2014-07-19T15:56:14Z",
    "facility_id": 60006382,
    "installer_id": 498338451,
    "job_id": 229136101,
    "licensed_runs": 200,
    "output_location_id": 60006382,
    "runs": 1,
    "start_date": "2014-07-19T15:47:06Z",
    "station_id": 60006382,
    "status": "active",
    "quantity_per_run": 100
  },
  ...
]
```

# Checklist

Check all boxes that apply to this issue:

- [X] Feature request description is provided
- [X] Use case exists
- [ ] Feature requires a new route
- [X] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [X] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Blacksmoke16** [comment]
Just to clarify I dont have strong feeling one way or another how this gets implemented.  Can discuss where it would be best to have it and can create another issue from there.  This was just the most obvious choice, but having it on the `/types/883/` would make more sense as i suggested in option 2.

**Comment by Aidansavage** [comment]
See also #501

**Comment by GoldenGnu** [comment]
I know this is a feature request. But, I still wanted to offer my help, just in the unlikely case anyone don't know how to do it with the SDE (Not as an alternative to the feature request).

ESI:
https://esi.evetech.net/ui/#/Universe/get_universe_types_type_id > `portion_size` will work for most things (not reactions and but, I think it will work with most/all manufacturing)

SDE:
`blueprints.yaml` 

```YAML
681:
    activities:
        copying:
            time: 480
        manufacturing:
            materials:
            -   quantity: 86
                typeID: 38
            products:
            -   quantity: 1 /* <== this is what you need for manufacturing */
                typeID: 165
            time: 600
        research_material:
            time: 210
        research_time:
            time: 210
    blueprintTypeID: 681
    maxProductionLimit: 300
/* ... */
45732:
    activities:
        reaction:
            materials:
            -   quantity: 100
                typeID: 16657
            -   quantity: 100
                typeID: 16661
            products:
            -   quantity: 20  /* <== this is what you need for reactions */
                typeID: 16672
            skills:
            -   level: 1
                typeID: 45746
            time: 360
    blueprintTypeID: 45732
    maxProductionLimit: 1000000
```
